// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: UploadDataHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: DeleteDataHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/query",
				Handler: QueryDataHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/data"),
	)
}
